# Generated by Django 4.1.1 on 2022-10-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=15)),
                ('booking_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Booking.booking')),
            ],
        ),
    ]
