# Generated by Django 4.1.1 on 2022-10-23 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_number', models.IntegerField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=50)),
                ('guest_address', models.CharField(max_length=100)),
                ('guest_country', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
